# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vittorio Palmisano
title_separator: "|"
email:
description: >- # this means to ignore newlines until "baseurl:"
  PhD | Staff Video Engineer | Full Stack
  More than 10y experience in developing and deploying applications for multimedia streaming and video conference services, including web, backend services, and cloud infrastructure.
#twitter_username: username
github_username: vpalmisano
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Vittorio Palmisano"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "PhD, Staff Video Engineer and Full Stack Developer"
  links:
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/vpalmisano"
  - label: "Medium"
    icon: "fab fa-fw fa-medium"
    url: "https://medium.com/@vpalmisano"
  - label: "Bluesky"
    icon: "fab fa-fw fa-bluesky"
    url: "https://bsky.app/profile/vpalmisano.bsky.social"

footer:
  links:
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/vpalmisano"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
